import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>under construction 🛠👷</h1>

        <p className={styles.description}>
          visit us again, have a nice day!
        </p>

        <div className={styles.grid}>
          <a target={"_blank"} href="https://github.com/stravo1" className={styles.card}>
            <h2>Github &rarr;</h2>
            <p>Checkout my Github and take a look at my projects!</p>
          </a>

          <a
            href="https://drive.google.com/uc?export=download&id=12cECmNNsjan0-wHYLIA0jwTsX7KEApJ5"
            className={styles.card}
          >
            <h2>Resume &rarr;</h2>
            <p>Take a look at my resume while you are here :)</p>
          </a>

        </div>
      </main>
    </div>
  );
}
